### ISSUE TITLE
What is the difference between the comprehensive code and release code

### ISSUE THREAD

**Issue by qian5683** [MAVIS-SLAM/ORB_SLAM3_MULTI#2]
Hi! Thank you for your excellent work in open source. Am I interested in it. If possible, I would like to know the difference between release code and comprehensive code. Thank you again for sharing!

**Comment by 1fwang** [comment]
Hi! The comprehensive code is not based on ORB-SLAM3, and the released code is an re-implementation of MAVIS on ORB-SLAM3 for demonstrate the concept and academic research. ORB_SLAM3_MULTI only include multi-camera setup and SE2(3) pre-integration.  Besides, data pre-processing and imu intrinsic compensation are not implemented in this version.
